"""Python file to populate database with fake data"""
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from database_setup import Base, Student, engine, Pref, Project

ENGINE = create_engine('sqlite:///database.db')
Base.metadata.bind = ENGINE
DBSESSION = sessionmaker(bind=ENGINE)
SESSION = DBSESSION()

"""Create and add projects A-H to database"""
project_A = Project(name='A')
project_B = Project(name='B')
project_C = Project(name='C')
project_D = Project(name='D')
project_E = Project(name='E')
project_F = Project(name='F')
project_G = Project(name='G')
project_H = Project(name='H')
project_none = Project(name='Not Matched')

SESSION.add(project_A)
SESSION.add(project_B)
SESSION.add(project_C)
SESSION.add(project_D)
SESSION.add(project_E)
SESSION.add(project_F)
SESSION.add(project_G)
SESSION.add(project_H)

SESSION.commit()

"""Create and add all students to database"""
Bob = Student(first_name='Bob', matched=0)
Joe = Student(first_name='Joe', matched=0)
Jack = Student(first_name='Jack', matched=0)
Jon = Student(first_name='Jon', matched=0)
Tim = Student(first_name='Tim', matched=0)
Rob = Student(first_name='Rob', matched=0)
Jim = Student(first_name='Jim', matched=0)
Tom = Student(first_name='Tom', matched=0)
James = Student(first_name='James', matched=0)
Jerry = Student(first_name='Jerry', matched=0)
Mike = Student(first_name='Mike', matched=0)
Mary = Student(first_name='Mary', matched=0)
Pat = Student(first_name='Pat', matched=0)
Jen = Student(first_name='Jen', matched=0)
Lin = Student(first_name='Lin', matched=0)
Liz = Student(first_name='Liz', matched=0)
Barb = Student(first_name='Barb', matched=0)
Susan = Student(first_name='Susan', matched=0)
Rick = Student(first_name='Rick', matched=0)
Will = Student(first_name='Will', matched=0)
Dan = Student(first_name='Dan', matched=0)
Lisa = Student(first_name='Lisa', matched=0)
Betty = Student(first_name='Betty', matched=0)
Kim = Student(first_name='Kim', matched=0)
Emily = Student(first_name='Emily', matched=0)
Ken = Student(first_name='Ken', matched=0)
Steph = Student(first_name='Steph', matched=0)
Laura = Student(first_name='Laura', matched=0)
Jason = Student(first_name='Jason', matched=0)

SESSION.add(Bob)
SESSION.add(Joe)
SESSION.add(Jack)
SESSION.add(Jon)
SESSION.add(Tim)
SESSION.add(Rob)
SESSION.add(Jim)
SESSION.add(Tom)
SESSION.add(James)
SESSION.add(Jerry)
SESSION.add(Mike)
SESSION.add(Mary)
SESSION.add(Pat)
SESSION.add(Jen)
SESSION.add(Lin)
SESSION.add(Liz)
SESSION.add(Barb)
SESSION.add(Susan)
SESSION.add(Rick)
SESSION.add(Will)
SESSION.add(Dan)
SESSION.add(Lisa)
SESSION.add(Betty)
SESSION.add(Kim)
SESSION.add(Emily)
SESSION.add(Ken)
SESSION.add(Steph)
SESSION.add(Laura)
SESSION.add(Jason)

SESSION.commit()

"""Create and add all prefs to database"""
Bob = SESSION.query(Student).filter_by(first_name='Bob').one()
Bob_first_pref = Pref(pref_number=1, name="A", student_id=1, student=Bob)
Bob_second_pref = Pref(pref_number=2, name="D", student_id=1, student=Bob)
SESSION.add(Bob_first_pref)
SESSION.add(Bob_second_pref)
SESSION.commit()

Joe = SESSION.query(Student).filter_by(first_name='Joe').one()
Joe_first_pref = Pref(pref_number=1, name="A", student_id=2, student=Joe)
Joe_second_pref = Pref(pref_number=2, name="E", student_id=2, student=Joe)
SESSION.add(Joe_first_pref)
SESSION.add(Joe_second_pref)
SESSION.commit()

Jack = SESSION.query(Student).filter_by(first_name='Jack').one()
Jack_first_pref = Pref(pref_number=1, name="C", student_id=3, student=Jack)
Jack_second_pref = Pref(pref_number=2, name="E", student_id=3, student=Jack)
SESSION.add(Jack_first_pref)
SESSION.add(Jack_second_pref)
SESSION.commit()

Jon = SESSION.query(Student).filter_by(first_name='Jon').one()
Jon_first_pref = Pref(pref_number=1, name="E", student_id=4, student=Jon)
Jon_second_pref = Pref(pref_number=2, name="F", student_id=4, student=Jon)
SESSION.add(Jon_first_pref)
SESSION.add(Jon_second_pref)
SESSION.commit()

Tim = SESSION.query(Student).filter_by(first_name='Tim').one()
Tim_first_pref = Pref(pref_number=1, name="H", student_id=5, student=Tim)
Tim_second_pref = Pref(pref_number=2, name="A", student_id=5, student=Tim)
SESSION.add(Tim_first_pref)
SESSION.add(Tim_second_pref)
SESSION.commit()

Rob = SESSION.query(Student).filter_by(first_name='Rob').one()
Rob_first_pref = Pref(pref_number=1, name="F", student_id=6, student=Rob)
Rob_second_pref = Pref(pref_number=2, name="A", student_id=6, student=Rob)
SESSION.add(Rob_first_pref)
SESSION.add(Rob_second_pref)
SESSION.commit()

Jim = SESSION.query(Student).filter_by(first_name='Jim').one()
Jim_first_pref = Pref(pref_number=1, name="C", student_id=7, student=Jim)
Jim_second_pref = Pref(pref_number=2, name="A", student_id=7, student=Jim)
SESSION.add(Jim_first_pref)
SESSION.add(Jim_second_pref)
SESSION.commit()

Tom = SESSION.query(Student).filter_by(first_name='Tom').one()
Tom_first_pref = Pref(pref_number=1, name="A", student_id=8, student=Tom)
Tom_second_pref = Pref(pref_number=2, name="C", student_id=8, student=Tom)
SESSION.add(Tom_first_pref)
SESSION.add(Tom_second_pref)
SESSION.commit()

James = SESSION.query(Student).filter_by(first_name='James').one()
James_first_pref = Pref(pref_number=1, name="C", student_id=9, student=James)
James_second_pref = Pref(pref_number=2, name="F", student_id=9, student=James)
SESSION.add(James_first_pref)
SESSION.add(James_second_pref)
SESSION.commit()

Jerry = SESSION.query(Student).filter_by(first_name='Jerry').one()
Jerry_first_pref = Pref(pref_number=1, name="E", student_id=10, student=Jerry)
Jerry_second_pref = Pref(pref_number=2, name="C", student_id=10, student=Jerry)
SESSION.add(Jerry_first_pref)
SESSION.add(Jerry_second_pref)
SESSION.commit()

Mike = SESSION.query(Student).filter_by(first_name='Mike').one()
Mike_first_pref = Pref(pref_number=1, name="F", student_id=11, student=Mike)
Mike_second_pref = Pref(pref_number=2, name="C", student_id=11, student=Mike)
SESSION.add(Mike_first_pref)
SESSION.add(Mike_second_pref)
SESSION.commit()

Mary = SESSION.query(Student).filter_by(first_name='Mary').one()
Mary_first_pref = Pref(pref_number=1, name="G", student_id=12, student=Mary)
Mary_second_pref = Pref(pref_number=2, name="D", student_id=12, student=Mary)
SESSION.add(Mary_first_pref)
SESSION.add(Mary_second_pref)
SESSION.commit()

Pat = SESSION.query(Student).filter_by(first_name='Pat').one()
Pat_first_pref = Pref(pref_number=1, name="F", student_id=13, student=Pat)
Pat_second_pref = Pref(pref_number=2, name="E", student_id=13, student=Pat)
SESSION.add(Pat_first_pref)
SESSION.add(Pat_second_pref)
SESSION.commit()

Jen = SESSION.query(Student).filter_by(first_name='Jen').one()
Jen_first_pref = Pref(pref_number=1, name='G', student_id=14, student=Jen)
Jen_second_pref = Pref(pref_number=2, name="F", student_id=14, student=Jen)
SESSION.add(Jen_first_pref)
SESSION.add(Jen_second_pref)
SESSION.commit()

Lin = SESSION.query(Student).filter_by(first_name='Lin').one()
Lin_first_pref = Pref(pref_number=1, name="G", student_id=15, student=Lin)
Lin_second_pref = Pref(pref_number=2, name="D", student_id=15, student=Lin)
SESSION.add(Lin_first_pref)
SESSION.add(Lin_second_pref)
SESSION.commit()

Liz = SESSION.query(Student).filter_by(first_name='Liz').one()
Liz_first_pref = Pref(pref_number=1, name="F", student_id=16, student=Liz)
Liz_second_pref = Pref(pref_number=2, name="H", student_id=16, student=Liz)
SESSION.add(Liz_first_pref)
SESSION.add(Liz_second_pref)
SESSION.commit()

Barb = SESSION.query(Student).filter_by(first_name='Barb').one()
Barb_first_pref = Pref(pref_number=1, name="E", student_id=17, student=Barb)
Barb_second_pref = Pref(pref_number=2, name="G", student_id=17, student=Barb)
SESSION.add(Barb_first_pref)
SESSION.add(Barb_second_pref)
SESSION.commit()

Susan = SESSION.query(Student).filter_by(first_name='Susan').one()
Susan_first_pref = Pref(pref_number=1, name="C", student_id=18, student=Susan)
Susan_second_pref = Pref(pref_number=2, name="D", student_id=18, student=Susan)
SESSION.add(Susan_first_pref)
SESSION.add(Susan_second_pref)
SESSION.commit()

Rick = SESSION.query(Student).filter_by(first_name='Rick').one()
Rick_first_pref = Pref(pref_number=1, name="D", student_id=19, student=Rick)
Rick_second_pref = Pref(pref_number=2, name="C", student_id=19, student=Rick)
SESSION.add(Rick_first_pref)
SESSION.add(Rick_second_pref)
SESSION.commit()

Will = SESSION.query(Student).filter_by(first_name='Will').one()
Will_first_pref = Pref(pref_number=1, name="A", student_id=20, student=Will)
Will_second_pref = Pref(pref_number=2, name="D", student_id=20, student=Will)
SESSION.add(Will_first_pref)
SESSION.add(Will_second_pref)
SESSION.commit()

Dan = SESSION.query(Student).filter_by(first_name='Dan').one()
Dan_first_pref = Pref(pref_number=1, name="A", student_id=21, student=Dan)
Dan_second_pref = Pref(pref_number=2, name="C", student_id=21, student=Dan)
SESSION.add(Dan_first_pref)
SESSION.add(Dan_second_pref)
SESSION.commit()

lisa = SESSION.query(Student).filter_by(first_name='Lisa').one()
Lisa_first_pref = Pref(pref_number=1, name="C", student_id=22, student=Lisa)
Lisa_second_pref = Pref(pref_number=2, name="A", student_id=22, student=Lisa)
SESSION.add(Lisa_first_pref)
SESSION.add(Lisa_second_pref)
SESSION.commit()

Betty = SESSION.query(Student).filter_by(first_name='Betty').one()
Betty_first_pref = Pref(pref_number=1, name="C", student_id=23, student=Betty)
Betty_second_pref = Pref(pref_number=2, name="A", student_id=23, student=Betty)
SESSION.add(Betty_first_pref)
SESSION.add(Betty_second_pref)
SESSION.commit()

Kim = SESSION.query(Student).filter_by(first_name='Kim').one()
Kim_first_pref = Pref(pref_number=1, name="A", student_id=24, student=Kim)
Kim_second_pref = Pref(pref_number=2, name="D", student_id=24, student=Kim)
SESSION.add(Kim_first_pref)
SESSION.add(Kim_second_pref)
SESSION.commit()

Emily = SESSION.query(Student).filter_by(first_name='Emily').one()
Emily_first_pref = Pref(pref_number=1, name="D", student_id=25, student=Emily)
Emily_second_pref = Pref(pref_number=2, name="E", student_id=25, student=Emily)
SESSION.add(Emily_first_pref)
SESSION.add(Emily_second_pref)
SESSION.commit()

Ken = SESSION.query(Student).filter_by(first_name='Ken').one()
Ken_first_pref = Pref(pref_number=1, name="E", student_id=26, student=Ken)
Ken_second_pref = Pref(pref_number=2, name="F", student_id=26, student=Ken)
SESSION.add(Ken_first_pref)
SESSION.add(Ken_second_pref)
SESSION.commit()

Steph = SESSION.query(Student).filter_by(first_name='Steph').one()
Steph_first_pref = Pref(pref_number=1, name="F", student_id=27, student=Steph)
Steph_second_pref = Pref(pref_number=2, name="E", student_id=27, student=Steph)
SESSION.add(Steph_first_pref)
SESSION.add(Steph_second_pref)
SESSION.commit()

Laura = SESSION.query(Student).filter_by(first_name='Laura').one()
Laura_first_pref = Pref(pref_number=1, name="E", student_id=28, student=Laura)
Laura_second_pref = Pref(pref_number=2, name="C", student_id=28, student=Laura)
SESSION.add(Laura_first_pref)
SESSION.add(Laura_second_pref)
SESSION.commit()

Jason = SESSION.query(Student).filter_by(first_name='Jason').one()
Jason_first_pref = Pref(pref_number=1, name="D", student_id=29, student=Jason)
Jason_second_pref = Pref(pref_number=2, name="A", student_id=29, student=Jason)
SESSION.add(Jason_first_pref)
SESSION.add(Jason_second_pref)
SESSION.commit()
