from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from database_setup import Base, Student, engine, Pref, Project

engine = create_engine('sqlite:///database.db')
Base.metadata.bind = engine

DBSession = sessionmaker(bind=engine)
session = DBSession()

project_A = Project(name = 'A')
project_B = Project(name = 'B')
project_C = Project(name = 'C')
project_D = Project(name = 'D')
project_E = Project(name = 'E')
project_F = Project(name = 'F')
project_G = Project(name = 'G')
project_H = Project(name = 'H')

session.add(project_A)
session.add(project_B)
session.add(project_C)
session.add(project_D)
session.add(project_E)
session.add(project_F)
session.add(project_G)
session.add(project_H)

session.commit()

Bob = Student(first_name = 'Bob')
Joe = Student(first_name = 'Joe')
Jack = Student(first_name = 'Jack')
Jon = Student(first_name = 'Jon')
Tim = Student(first_name = 'Tim')
Rob = Student(first_name = 'Rob')
Jim = Student(first_name = 'Jim')
Tom = Student(first_name = 'Tom')
James = Student(first_name = 'James')
Jerry = Student(first_name = 'Jerry')
Mike = Student(first_name = 'Mike')
Mary = Student(first_name = 'Mary')
Pat = Student(first_name = 'Pat')
Jen = Student(first_name = 'Jen')
Lin = Student(first_name = 'Lin')
Liz = Student(first_name = 'Liz')
Barb = Student(first_name = 'Barb')
Susan = Student(first_name = 'Susan')
Rick = Student(first_name = 'Rick')
Will = Student(first_name = 'Will')
Dan = Student(first_name = 'Dan')
Lisa = Student(first_name = 'Lisa')
Betty = Student(first_name = 'Betty')
Kim = Student(first_name = 'Kim')
Emily = Student(first_name = 'Emily')
Ken = Student(first_name = 'Ken')
Steph = Student(first_name = 'Steph')
Laura = Student(first_name = 'Laura')
Jason = Student(first_name = 'Jason')

session.add(Bob)
session.add(Joe)
session.add(Jack)
session.add(Jon)
session.add(Tim)
session.add(Rob)
session.add(Jim)
session.add(Tom)
session.add(James)
session.add(Jerry)
session.add(Mike)
session.add(Mary)
session.add(Pat)
session.add(Jen)
session.add(Lin)
session.add(Liz)
session.add(Barb)
session.add(Susan)
session.add(Rick)
session.add(Will)
session.add(Dan)
session.add(Lisa)
session.add(Betty)
session.add(Kim)
session.add(Emily)
session.add(Ken)
session.add(Steph)
session.add(Laura)
session.add(Jason)

session.commit()

Bob = session.query(Student).filter_by(first_name = 'Bob').one()
Bob_first_pref = Pref(pref_number = 1, name = "A", student_id = 1, student = Bob)
Bob_second_pref = Pref(pref_number = 2, name = "D", student_id = 1, student = Bob)
session.add(Bob_first_pref)
session.add(Bob_second_pref)
session.commit()

Joe = session.query(Student).filter_by(first_name = 'Joe').one()
Joe_first_pref = Pref(pref_number = 1, name = "A", student_id = 2, student = Joe)
Joe_second_pref = Pref(pref_number = 2, name = "E", student_id = 2, student = Joe)
session.add(Joe_first_pref)
session.add(Joe_second_pref)
session.commit()

Jack = session.query(Student).filter_by(first_name = 'Jack').one()
Jack_first_pref = Pref(pref_number = 1, name = "C", student_id = 3, student = Jack)
Jack_second_pref = Pref(pref_number = 2, name = "E", student_id = 3, student = Jack)
session.add(Jack_first_pref)
session.add(Jack_second_pref)
session.commit()

Jon = session.query(Student).filter_by(first_name = 'Jon').one()
Jon_first_pref = Pref(pref_number = 1, name = "E", student_id = 4, student = Jon)
Jon_second_pref = Pref(pref_number = 2, name = "F", student_id = 4, student = Jon)
session.add(Jon_first_pref)
session.add(Jon_second_pref)
session.commit()

Tim = session.query(Student).filter_by(first_name = 'Tim').one()
Tim_first_pref = Pref(pref_number = 1, name = "H", student_id = 5, student = Tim)
Tim_second_pref = Pref(pref_number = 2, name = "A", student_id = 5, student = Tim)
session.add(Tim_first_pref)
session.add(Tim_second_pref)
session.commit()

Rob = session.query(Student).filter_by(first_name = 'Rob').one()
Rob_first_pref = Pref(pref_number = 1, name = "F", student_id = 6, student = Rob)
Rob_second_pref = Pref(pref_number = 2, name = "A", student_id = 6, student = Rob)
session.add(Rob_first_pref)
session.add(Rob_second_pref)
session.commit()

Jim = session.query(Student).filter_by(first_name = 'Jim').one()
Jim_first_pref = Pref(pref_number = 1, name = "C", student_id = 7, student = Jim)
Jim_second_pref = Pref(pref_number = 2, name = "A", student_id = 7, student = Jim)
session.add(Jim_first_pref)
session.add(Jim_second_pref)
session.commit()

Tom = session.query(Student).filter_by(first_name = 'Tom').one()
Tom_first_pref = Pref(pref_number = 1, name = "A", student_id = 8, student = Tom)
Tom_second_pref = Pref(pref_number = 2, name = "C", student_id = 8, student = Tom)
session.add(Tom_first_pref)
session.add(Tom_second_pref)
session.commit()

James = session.query(Student).filter_by(first_name = 'James').one()
James_first_pref = Pref(pref_number = 1, name = "C", student_id = 9, student = James)
James_second_pref = Pref(pref_number = 2, name = "F", student_id = 9, student = James)
session.add(James_first_pref)
session.add(James_second_pref)
session.commit()

Jerry = session.query(Student).filter_by(first_name = 'Jerry').one()
Jerry_first_pref = Pref(pref_number = 1, name = "E", student_id = 10, student = Jerry)
Jerry_second_pref = Pref(pref_number = 2, name = "C", student_id = 10, student = Jerry)
session.add(Jerry_first_pref)
session.add(Jerry_second_pref)
session.commit()

Mike = session.query(Student).filter_by(first_name = 'Mike').one()
Mike_first_pref = Pref(pref_number = 1, name = "F", student_id = 11, student = Mike)
Mike_second_pref = Pref(pref_number = 2, name = "C", student_id = 11, student = Mike)
session.add(Mike_first_pref)
session.add(Mike_second_pref)
session.commit()

Mary = session.query(Student).filter_by(first_name = 'Mary').one()
Mary_first_pref = Pref(pref_number = 1, name = "G", student_id = 12, student = Mary)
Mary_second_pref = Pref(pref_number = 2, name = "D", student_id = 12, student = Mary)
session.add(Mary_first_pref)
session.add(Mary_second_pref)
session.commit()

Pat = session.query(Student).filter_by(first_name = 'Pat').one()
Pat_first_pref = Pref(pref_number = 1, name = "F", student_id = 13, student = Pat)
Pat_second_pref = Pref(pref_number = 2, name = "E", student_id = 13, student = Pat)
session.add(Pat_first_pref)
session.add(Pat_second_pref)
session.commit()

Jen = session.query(Student).filter_by(first_name = 'Jen').one()
Jen_first_pref = Pref(pref_number = 1, name = 'G', student_id = 14, student = Jen)
Jen_second_pref = Pref(pref_number = 2, name = "F", student_id = 14, student = Jen)
session.add(Jen_first_pref)
session.add(Jen_second_pref)
session.commit()

Lin = session.query(Student).filter_by(first_name = 'Lin').one()
Lin_first_pref = Pref(pref_number = 1, name = "G", student_id = 15, student = Lin)
Lin_second_pref = Pref(pref_number = 2, name = "D", student_id = 15, student = Lin)
session.add(Lin_first_pref)
session.add(Lin_second_pref)
session.commit()

Liz = session.query(Student).filter_by(first_name = 'Liz').one()
Liz_first_pref = Pref(pref_number = 1, name = "F", student_id = 16, student = Liz)
Liz_second_pref = Pref(pref_number = 2, name = "H", student_id = 16, student = Liz)
session.add(Liz_first_pref)
session.add(Liz_second_pref)
session.commit()

Barb = session.query(Student).filter_by(first_name = 'Barb').one()
Barb_first_pref = Pref(pref_number = 1, name = "E", student_id = 17, student = Barb)
Barb_second_pref = Pref(pref_number = 2, name = "G", student_id = 17, student = Barb)
session.add(Barb_first_pref)
session.add(Barb_second_pref)
session.commit()

Susan = session.query(Student).filter_by(first_name = 'Susan').one()
Susan_first_pref = Pref(pref_number = 1, name = "C", student_id = 18, student = Susan)
Susan_second_pref = Pref(pref_number = 2, name = "D", student_id = 18, student = Susan)
session.add(Susan_first_pref)
session.add(Susan_second_pref)
session.commit()

Rick = session.query(Student).filter_by(first_name = 'Rick').one()
Rick_first_pref = Pref(pref_number = 1, name = "D", student_id = 19, student = Rick)
Rick_second_pref = Pref(pref_number = 2, name = "C", student_id = 19, student = Rick)
session.add(Rick_first_pref)
session.add(Rick_second_pref)
session.commit()

Will = session.query(Student).filter_by(first_name = 'Will').one()
Will_first_pref = Pref(pref_number = 1, name = "A", student_id = 20, student = Will)
Will_second_pref = Pref(pref_number = 2, name = "D", student_id = 20, student = Will)
session.add(Will_first_pref)
session.add(Will_second_pref)
session.commit()

Dan = session.query(Student).filter_by(first_name = 'Dan').one()
Dan_first_pref = Pref(pref_number = 1, name = "A", student_id = 21, student = Dan)
Dan_second_pref = Pref(pref_number = 2, name = "C", student_id = 21, student = Dan)
session.add(Dan_first_pref)
session.add(Dan_second_pref)
session.commit()

lisa = session.query(Student).filter_by(first_name = 'Lisa').one()
Lisa_first_pref = Pref(pref_number = 1, name = "C", student_id = 22, student = Lisa)
Lisa_second_pref = Pref(pref_number = 2, name = "A", student_id = 22, student = Lisa)
session.add(Lisa_first_pref)
session.add(Lisa_second_pref)
session.commit()

Betty = session.query(Student).filter_by(first_name = 'Betty').one()
Betty_first_pref = Pref(pref_number = 1, name = "C", student_id = 23, student = Betty)
Betty_second_pref = Pref(pref_number = 2, name = "A", student_id = 23, student = Betty)
session.add(Betty_first_pref)
session.add(Betty_second_pref)
session.commit()

Kim = session.query(Student).filter_by(first_name = 'Kim').one()
Kim_first_pref = Pref(pref_number = 1, name = "A", student_id = 24, student = Kim)
Kim_second_pref = Pref(pref_number = 2, name = "D", student_id = 24, student = Kim)
session.add(Kim_first_pref)
session.add(Kim_second_pref)
session.commit()

Emily = session.query(Student).filter_by(first_name = 'Emily').one()
Emily_first_pref = Pref(pref_number = 1, name = "D", student_id = 25, student = Emily)
Emily_second_pref = Pref(pref_number = 2, name = "E", student_id = 25, student = Emily)
session.add(Emily_first_pref)
session.add(Emily_second_pref)
session.commit()

Ken = session.query(Student).filter_by(first_name = 'Ken').one()
Ken_first_pref = Pref(pref_number = 1, name = "E", student_id = 26, student = Ken)
Ken_second_pref = Pref(pref_number = 2, name = "F", student_id = 26, student = Ken)
session.add(Ken_first_pref)
session.add(Ken_second_pref)
session.commit()

Steph = session.query(Student).filter_by(first_name = 'Steph').one()
Steph_first_pref = Pref(pref_number = 1, name = "F", student_id = 27, student = Steph)
Steph_second_pref = Pref(pref_number = 2, name = "E", student_id = 27, student = Steph)
session.add(Steph_first_pref)
session.add(Steph_second_pref)
session.commit()

Laura = session.query(Student).filter_by(first_name = 'Laura').one()
Laura_first_pref = Pref(pref_number = 1, name = "E", student_id = 28, student = Laura)
Laura_second_pref = Pref(pref_number = 2, name = "C", student_id = 28, student = Laura)
session.add(Laura_first_pref)
session.add(Laura_second_pref)
session.commit()

Jason = session.query(Student).filter_by(first_name = 'Jason').one()
Jason_first_pref = Pref(pref_number = 1, name = "D", student_id = 29, student = Jason)
Jason_second_pref = Pref(pref_number = 2, name = "A", student_id = 29, student = Jason)
session.add(Jason_first_pref)
session.add(Jason_second_pref)
session.commit()
