"""Python file to populate database with project data from 2019"""
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from database_setup import Base, Student, engine, Pref, Project

ENGINE = create_engine('mysql+pymysql://chadwick:godolphins@apex-matching.c0plu8oomro4.us-east-2.rds.amazonaws.com:3306/testdb')
Base.metadata.bind = ENGINE
DBSESSION = sessionmaker(bind=ENGINE)
session = DBSESSION()

# Session 1 Projects
A = Project(name='Identity Theft Is Not a Joke, Jim!: Why Millions of Families Suffer Every Year: David Malone', session_number=1)
B = Project(name='The True Price of a College Education: The Crippling Long-Term Effects of Student Loans: Jessie Doty', session_number=1)
C = Project(name='E-cigarettes: An Adolescent Epidemic: Eugene Moon', session_number=1)
D = Project(name='Can\'t Sit Still? You\'re Not Alone ... And It\'s Not Entirely Your Fault: Morgan Brandmeyer', session_number=1)
E = Project(name='Making a Man: Toxic Masculinity: Alex Rosso', session_number=1)
F = Project(name='Our Mighty Mascot, the Bottlenose Dolphin: The Flaws in our Recycling Habits: Macy Dimson', session_number=1)
G = Project(name='We\'re Human, Too: Combatting Anti-Semitism in the Los Angeles Area: Sam Bogen', session_number=1)
H = Project(name='I Hate Chadwick: Unpacking and Addressing Negativity Among the Student Body: Lizzie Davis', session_number=1)
I = Project(name='Plugging Into the Future: Electric Vehicle Charging at Chadwick: C.B. Frey', session_number=1)
J = Project(name='Bunnies are Beautiful Without Makeup: Animal Testing of Cosmetics: Mary Bernadett', session_number=1)
K = Project(name='Save the Bees of Manhattan Beach: Tucker Hale', session_number=1)
L = Project(name='#WhatIsYourBodyImage?: Caitlin Wolf', session_number=1)
M = Project(name='Mental Health and Entertainment: A Beneficial Correlation: Nick Tell', session_number=1)
N = Project(name='Sex Ed Isn’t Just for Heterosexuals: Creating a More Inclusive Sexual Health Curriculum for All Students: Margot Bradshaw', session_number=1)
O = Project(name='Students on the Spectrum in College: How to Help Them Succeed: Jonathan Wohl', session_number=1)
P = Project(name='To Not Partake in the \"Ted Bundy is Hot\" Movement: Shannon Chung', session_number=1)
Q = Project(name='Clean Up, Clean Up, Every Dolphin Everywhere: The Clean Chadwick Challenge: Mike Hodgkiss', session_number=1)
R = Project(name='Every Student, Every Day: Utilizing Leadership to Cure Chronic Absenteeism: Alexa Schwake', session_number=1)
S = Project(name='The Growing Problem of Invasive Species: How America’s Natural Resources Are Being Eaten Alive: Bryan Regan', session_number=1)
T = Project(name='Creating Young Artists: Bringing Art Back to Schools: Klark White', session_number=1)
U = Project(name='Why \"Red vs. Blue\" Becomes \"Me vs. You\": Aidan Tyssee', session_number=1)
V = Project(name='Shatter the Stigma: Normalizing Mental Health Conversations: Allison Coward', session_number=1)
W = Project(name='Is College An Option For All Of Us?: Latinos In Higher Education: Sam Rivas', session_number=1)
X = Project(name='Ryan\'s Guide to Succeeding at Work: Ryan Hom', session_number=1)

# Session 2 Projects
Y = Project(name='Our Trash: Chloe Lin', session_number=2)
Z = Project(name='Water ... a Right or a Privilege?: Lead in LAUSD Schools\' Water: Jack Connelly', session_number=2)
AA = Project(name='Are You Depressed?: Making Long-Term Treatment Accessible to the Chadwick Community: Katie Eu', session_number=2)
AB = Project(name='Political Polarization: It\'s Not Black and White—It\'s Red and Blue: Jordan Yang', session_number=2)
AC = Project(name='Human Rights. Period: Why Everyone Should Have Access to Feminine Care Products: Alex Davisson', session_number=2)
AD = Project(name='Clash of Cultures: How Americans Find Their Cultural Identity: Race Cameron', session_number=2)
AE = Project(name='Is Chadwick a \"Rich Kid\" School?: Lack of Discussion around Socioeconomic Class in Elite Independent Schools: Vetta Angelow', session_number=2)
AF = Project(name='MAST: Fighting Human Trafficking at Sea: Caden Moskowitz', session_number=2)
AG = Project(name='There is no Plan(et) B: Fostering Student Leadership through Environmental Stewardship in K-12 Schools as the Future of Education: Taryn Gurbach', session_number=2)
AH = Project(name='Turning Streetwear into Progress: The Importance of Being Socially Responsible: Jeffrey Zhang', session_number=2)
AI = Project(name='Everyone Hate$ the College Board: The $truggle with Inequity in the College Proce$$: Marin Tchen', session_number=2)
AJ = Project(name='Sleep Deprivation: A Modern Epidemic: Cameron Davodi', session_number=2)
AK = Project(name='A Quiet Place: Creating Silent Study Environments for Students: Mia Dimson', session_number=2)
AL = Project(name='The Black Truth: A Black Student\'s Perspective at Chadwick: Duke Lindsey', session_number=2)
AM = Project(name='Legalized Animal Cruelty?: The Complexities of the Animal Agricultural Industry: Julia Moorefield', session_number=2)
AN = Project(name='Just Flip That Switch! Reducing Chadwick\'s Energy Consumption: Grant Ho', session_number=2)
AO = Project(name='6 Figures in 15 Minutes: Smart Financial Education for the Future: Neville Linden', session_number=2)
AP = Project(name='The Stories We Tell Ourselves: A Linguistic Review of Youth Mental Health Decline: Kate Borden', session_number=2)
AQ = Project(name='Dance Dance Revolution: Dance’s Impact on Athletic Performance: KC Chambers', session_number=2)
AR = Project(name='The Sixth Extinction: How It Affects Insects: Brodrick Laird', session_number=2)
AS = Project(name='Stitching Up the Cultural Gap: How to Improve Low-Income Patient Experience: Amber Zheng', session_number=2)
AT = Project(name='Is Literature LIT?: Implementing Pleasure Reading Into the English Curriculum: Anandi Choudhury', session_number=2)

# Session 3 Projects
AU = Project(name='Programming Your Mind:  How To Edit Habits', session_number=3)
AV = Project(name='JAWS: Fixing Sharks Bad Reputations', session_number=4)
AW = Project(name='AllRight: observing extreme political partisanship through FaceBook', session_number=1)
AX = Project(name='Helping Hospitalized Children Cope with Stress', session_number=2)
AY = Project(name='Out of Tune: Revamping the Chadwick Instrumental Program', session_number=3)
AZ = Project(name='Solar Freakin Umbrellas: Implementing Solar Technology at Chadwick', session_number=4)
BA = Project(name='A Salute to Service Dogs', session_number=1)
BB = Project(name='Go the Frick to Sleep, You Fricking Fricks', session_number=2)
BC = Project(name='Not just a Brazilian Butt Workout: Another Type of Workout Vide', session_number=3)
BD = Project(name='Dancing in the rain during a drought: a water conservation guide for daily life', session_number=4)
BE = Project(name='From Assistants to Physicists: The Pursuit of Equality in STEM', session_number=1)
BF = Project(name='Guys And Dolls: A Look At Gendered Marketing Of Childrens Products', session_number=2)
BG = Project(name='Color Your Way Towards Happiness', session_number=3)
BH = Project(name='The California Coastline Takeover: Invasive Seaweed', session_number=4)
BI = Project(name='There Will Be Blood: Preventing Type 1 Diabetes Misdiagnosis', session_number=1)
BJ = Project(name='Stamping out Sexism in the Elementary School Classroom', session_number=2)
BK = Project(name='Capture Water Before it Goes', session_number=3)
BL = Project(name='Spotlight on the Students: Fostering Creativity in Chadwicks Stage Crew', session_number=4)
BM = Project(name='Why Should You be Grateful for Chadwick?', session_number=1)
BN = Project(name='Zoos: Born to be Wild', session_number=2)
BO = Project(name='How Many Bunnies Died for your Chapstick? Exposing Animal Testing in Cosmetics', session_number=3)
BP = Project(name='The ART of De-Stressing: Using Creativity to Promote Wellness', session_number=4)
BQ = Project(name='F#### of S####: What Can You Legally Say On Chadwicks Campus?', session_number=1)
BR = Project(name='Building Relationship with Children in Foster Care', session_number=2)
BS = Project(name='Protecting the Protected: Safeguarding Marine Protected Areas', session_number=3)
BT = Project(name='Infusing Objectivity and Individualism into Educating the Global Citizen', session_number=4)
BU = Project(name='Balancing the Numbers:  Supporting Female Engineers at Chadwick', session_number=1)
BV = Project(name='Are you a boy, girl, or other?: The importance of gender inclusion at school', session_number=2)
BW = Project(name='Empowering Girls in India Through Education', session_number=3)
BX = Project(name='Putting the Anti in Antibiotic Meat: The Pitfalls of Antibiotic Usage in Livestock Farming for Human Health and the Environment', session_number=4)
BY = Project(name='Protect Yourself Before You Wreck Yourself: The Dangers of Lifelong Sun Damage', session_number=1)
BZ = Project(name='Meditation: Methods to relieve stress and improve personal condition', session_number=2)
CA = Project(name='Fake News: the Cancer of Our Democracy', session_number=3)
CB = Project(name='What Happens To Homeless Pets In Our World', session_number=4)
CC = Project(name='Media and User Bias in the Digital Age: What You Can Do to Beat It', session_number=1)
CD = Project(name='Click on Sustainability: Reducing Your Carbon Footprint in Los Angeles', session_number=2)
CE = Project(name='Why Excessive Homework is Bad for High School Students', session_number=3)
CF = Project(name='Oh Brother!: The Conveniences and Costs of Mass Surveillance', session_number=4)
CG = Project(name='The Myth of Car Idling', session_number=1)
CH = Project(name='Need a hand? Providing a list of babysitters for families dealing with pediatric cancer', session_number=2)
CI = Project(name='"Youre So Pretty for a Black Girl": The Problem With White Beauty Ideals', session_number=3)
CJ = Project(name='Addressing Homelessness in My Community', session_number=4)
CK = Project(name='Mental Health: What do All Faculty Need to Know', session_number=1)
CL = Project(name='Healthy Habits To-Go: Ways to Efficiently Maintain a Balanced Lifestyle', session_number=2)
CM = Project(name='Addressing the Systemic Risk of the Big Three: Depression, Anxiety, and Drug Abuse', session_number=3)
CN = Project(name='The Quality of Life in Spinal Muscular Atrophy Children', session_number=4)
CO = Project(name='Kids These Days: Why Arent They Active?', session_number=1)
CP = Project(name='This Book Could Change Your Life: Combating Homophobia One Book at a Time', session_number=2)
CQ = Project(name='The Importance of Media Literacy in the Digital Age', session_number=3)
CR = Project(name='Apex under a Microscope: Employing Empathy to Ensure the Success of Chadwick Apex Projects', session_number=4)
CS = Project(name='Expanding the Admirals Role in the Chadwick Community', session_number=1)
none = Project(name='Not Matched', session_number=2)
session.add(A)
session.add(B)
session.add(C)
session.add(D)
session.add(E)
session.add(H)
session.add(I)
session.add(J)
session.add(K)
session.add(L)
session.add(M)
session.add(N)
session.add(O)
session.add(P)
session.add(Q)
session.add(R)
session.add(S)
session.add(T)
session.add(U)
session.add(V)
session.add(W)
session.add(X)
session.add(Y)
session.add(Z)
session.add(AA)
session.add(AB)
session.add(AC)
session.add(AD)
session.add(AE)
session.add(AF)
session.add(AG)
session.add(AH)
session.add(AI)
session.add(AJ)
session.add(AK)
session.add(AL)
session.add(AM)
session.add(AN)
session.add(AO)
session.add(AP)
session.add(AQ)
session.add(AR)
session.add(AS)
session.add(AT)
session.add(AU)
session.add(AV)
session.add(AW)
session.add(AX)
session.add(AY)
session.add(AZ)
session.add(BA)
session.add(BB)
session.add(BC)
session.add(BD)
session.add(BE)
session.add(BF)
session.add(BG)
session.add(BH)
session.add(BI)
session.add(BJ)
session.add(BK)
session.add(BL)
session.add(BM)
session.add(BN)
session.add(BO)
session.add(BP)
session.add(BQ)
session.add(BR)
session.add(BS)
session.add(BT)
session.add(BU)
session.add(BV)
session.add(BW)
session.add(BX)
session.add(BY)
session.add(BZ)
session.add(CA)
session.add(CB)
session.add(CC)
session.add(CD)
session.add(CE)
session.add(CF)
session.add(CG)
session.add(CH)
session.add(CI)
session.add(CJ)
session.add(CK)
session.add(CL)
session.add(CM)
session.add(CN)
session.add(CO)
session.add(CP)
session.add(CQ)
session.add(CR)
session.add(CS)
session.commit()
